name: "EfficientNetv2 S Imagenette single pipeline benchmark with preprocessing in dataloader"
pipelines:
  - name: EfficientNetv2 S Imagenette
    inputs: [0]
    outputs: [2]
    loadgen:
      type: poisson
      max_queries: 200
      timeout: 30
      config:
        rate: 10 # average #requests/sec
    stages:
      - name: Imagenette dataset
        id: 0
        outputs: [1]
        type: dataset
        module_name: torchvision_dataset
        config:
          dataset_name: Imagenette # must be title-case
          split: [val]
          batch_size: 1
          weights: EfficientNet_V2_S_Weights.IMAGENET1K_V1
      - name: Load Imagenette samples from TorchVision Dataset
        id: 1
        inputs: [0]
        outputs: [2]
        type: data_loading
        module_name: torch_from_dataset
        ingest_dataset: True
        config:
          batch_size: 1
          num_workers: 0 # if 0 no prefetching else prefetches 2*num_workers samples
          preprocessing: True
      - name: EfficientNet inference
        id: 2
        inputs: [1]
        type: inference
        module_name: torchvision_classification
        config:
          model: efficientnet_v2_s
          model_checkpoint_path: "efficientnet_example/efficientnet_v2_imagenette.pth"
          replace_classifier: True
          num_classes: 10
