name: "PHI3 Mini Alpaca generation pipeline"
pipelines:
  - name: Alpaca generation
    inputs: [0]
    outputs: [1]
    loadgen:
      component: loadgen.PoissonLoadScheduler
      queue_depth: 10
      max_queries: 2000
      timeout: 20000
      config:
        rate: 1 # average #requests/sec
    stages:
      - name: Alpaca dataloader
        id: 0
        outputs: [1]
        component: stages.llm_torchtune.TorchTuneDataLoader
        config:
          batch_size: 16
          shuffle: True
          split: ["val"]
          dataset:
            component: torchtune.datasets.alpaca_cleaned_dataset
          tokenizer:
            component: torchtune.models.phi3.phi3_mini_tokenizer
            path: tmp/phi3-mini-4k/tokenizer.model
      - name: Alpaca inference
        id: 1
        component: stages.llm_torchtune.Inference
        config: 
          dtype: torch.bfloat16
          device: cuda
          temperature: 0.6
          top_k: 300
          max_new_tokens: 300
          batch_size_stage_id: 1
          model:
            component: torchtune.models.phi3.phi3_mini
          checkpointer:
            component: torchtune.utils.FullModelHFCheckpointer
            checkpoint_dir: tmp/phi3-mini-4k
            checkpoint_files: [
              model-00001-of-00002.safetensors,
              model-00002-of-00002.safetensors
            ]
            output_dir: tmp/phi3-mini-4k
            model_type: PHI3_MINI