name: "PHI3 Mini Alpaca finetuning pipeline"
pipelines:
  - name: Alpaca finetuning
    inputs: [0]
    outputs: [1]
    loadgen:
      type: offline
      max_queries: 2000
      is_training: True
      timeout: 20000
      config:
        rate: 1 # average #requests/sec
    stages:
      - name: Alpaca dataloader
        id: 0
        outputs: [1]
        component: stages.llm_torchtune.TorchTuneDataLoader
        config:
          loss_fn_stage_id: 1
          batch_size: 2
          shuffle: True
          split: ["train"]
          dataset:
            component: torchtune.datasets.alpaca_cleaned_dataset
          tokenizer:
            component: torchtune.models.phi3.phi3_mini_tokenizer
            path: tmp/phi3-mini-4k/tokenizer.model
      - name: Alpaca finetune
        id: 1
        component: stages.llm_torchtune.Finetune
        config: 
          dtype: torch.bfloat16
          device: cuda
          model:
            component: torchtune.models.phi3.qlora_phi3_mini
            lora_attn_modules: ['q_proj', 'v_proj', 'k_proj', 'output_proj']
            apply_lora_to_mlp: True
            apply_lora_to_output: False
            lora_rank: 8
            lora_alpha: 16
          checkpointer:
            component: torchtune.utils.FullModelHFCheckpointer
            checkpoint_dir: tmp/phi3-mini-4k
            checkpoint_files: [
              model-00001-of-00002.safetensors,
              model-00002-of-00002.safetensors
            ]
            output_dir: tmp/phi3-mini-4k
            model_type: PHI3_MINI
          optimizer:
            component: torch.optim.AdamW
            weight_decay: 0.01
            lr: 3.0e-4
          lr_scheduler:
            component: torchtune.modules.get_cosine_schedule_with_warmup
            num_warmup_steps: 100
          loss:
            component: torch.nn.CrossEntropyLoss
          gradient_accumulation_steps: 16