name: "Self RAG with DuckDB connection"
pipelines:
  - name: Self RAG
    inputs: [0]
    outputs: [1]
    dataset_stage_id: 0
    loadgen:
      component: loadgen.OfflineLoadScheduler
      queue_depth: 10
      max_queries: 4
      timeout: 20000
      config:
        rate: 1 # average #requests/sec
    stages:
      - name: Mock dataloader
        id: 0
        outputs: [1]
        component: stages.llm_huggingface.MockDataLoader  
        config:
          tokenizer_stage_id: 1
          batch_size: 1
          shuffle: True
          split: ["train"]
          dataset:
            name: yahma/alpaca-cleaned
            system_column_name: instruction
            user_column_name: input
            assistant_column_name: output
      - name: SQLite query
        id: 1
        component: stages.self_rag.SQLiteSearch
        config:
          db_path: tmp/accounting.sqlite